### ISSUE TITLE
Cannot export with name or region

### ISSUE THREAD

**Issue by jmichaelodell** [colin0brass/FaceLabellingExportLrPlugin#11]
I downloaded and installed the various versions of the plugin and cannot seem to get the names and or face region to show up on the exported photo. I initially started with the latest version of LR and downgraded to 10.1.1 to no avail. I have read through the issues and was not able to get the plugin to work. I am happy to try things if you have any ideas. I should also mention I am on a MacBook M1 and am running Monterey 12.2.

**Comment by colin0brass** [comment]
Interesting. I've not tried it on M1 yet, but I do have one. I'll see if I
can try it this weekend. Thanks for flagging.

**Comment by colin0brass** [comment]
Sorry it took me longer than I expected to get back to this.
I tested it on M1 today with Monterey 12.2.1, and LightRoom 11.2.

I found and fixed two issues - one with handling of an empty label experiment list, and the other frustratingly simply in the debug logging function during early plugin-initialisation before the logger is fully initialised. I also took the opportunity to add a button to reset the plugin stored preference values back to nil to enable testing as per first clean install.

In my M1 testing I successfully used the same ExifTool version that was already bundled in the plugin. I also happened to try ExifTool installed using homebrew (to: /opt/homebrew/bin/exiftool) and that worked too. For ImageMagick I installed that using homebrew and found the paths to configure in plugin manager for my installation were: /opt/homebrew/bin/magick; and: /opt/homebrew/bin/convert

I have published a release v1.9 to GitHub.

Please could you give this a try and see if it now works correctly for you?

**Comment by jmichaelodell** [comment]
So I tested it and with the logs was able to find I had an ImageMagick install issue which when corrected allowed th plugin to work great. Thank you

**Comment by colin0brass** [comment]
That's good news. Thank you for letting me know.
